object CalculatorGUIForm: TCalculatorGUIForm
  Left = 0
  Top = 0
  Caption = 'CalculatorGUIForm'
  ClientHeight = 153
  ClientWidth = 400
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object DisplayArea: TMemo
    Left = 0
    Top = 0
    Width = 400
    Height = 153
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
  end
end
